# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.2)
GMASH_SUBTREE_ARGR=''
gmash_parser_subtree() {
	OPTIND=$(($#+1))
	while OPTARG= && [ "${GMASH_SUBTREE_ARGR}" != x ] && [ $# -gt 0 ]; do
		set -- "${1%%\=*}" "${1#*\=}" "$@"
		while [ ${#1} -gt 2 ]; do
			case $1 in (*[!a-zA-Z0-9_-]*) break; esac
			case '--help' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --help"
			esac
			case '--version' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --version"
			esac
			break
		done
		case ${OPTARG# } in
			*\ *)
				eval "set -- $OPTARG $1 $OPTARG"
				OPTIND=$((($#+1)/2)) OPTARG=$1; shift
				while [ $# -gt "$OPTIND" ]; do OPTARG="$OPTARG, $1"; shift; done
				set "Ambiguous option: $1 (could be $OPTARG)" ambiguous "$@"
				parser_error "$@" >&2 || exit $?
				echo "$1" >&2
				exit 1 ;;
			?*)
				[ "$2" = "$3" ] || OPTARG="$OPTARG=$2"
				shift 3; eval 'set -- "${OPTARG# }"' ${1+'"$@"'}; OPTARG= ;;
			*) shift 2
		esac
		case $1 in
			--?*=*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
				;;
			--no-*|--without-*) unset OPTARG ;;
			-[hv]?*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
				case $2 in --*) set -- "$1" unknown "$2" && GMASH_SUBTREE_ARGR=x; esac;OPTARG= ;;
			+*) unset OPTARG ;;
		esac
		case $1 in
			'-h'|'--help')
				gmash_subtree_help
				exit 0 ;;
			'-v'|'--version')
				echo "${GMASH_SUBTREE_VERSION}"
				exit 0 ;;
			--)
				while [ $# -gt 0 ]; do
					GMASH_SUBTREE_ARGR="${GMASH_SUBTREE_ARGR} \"\${$(($OPTIND-$#))}\""
					shift
				done
				break ;;
			[-+]?*) set "unknown" "$1"; break ;;
			*)
				case $1 in 'new'|'patch') ;;
					*) set "notcmd" "$1"; break
				esac
				while [ $# -gt 0 ]; do
					GMASH_SUBTREE_ARGR="${GMASH_SUBTREE_ARGR} \"\${$(($OPTIND-$#))}\""
					shift
				done
				break ;;
		esac
		shift
	done
	[ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
	case $1 in
		unknown) set "Unrecognized option: $2" "$@" ;;
		noarg) set "Does not allow an argument: $2" "$@" ;;
		required) set "Requires an argument: $2" "$@" ;;
		pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
		notcmd) set "Not a command: $2" "$@" ;;
		*) set "Validation error ($1): $2" "$@"
	esac
	parser_error "$@" >&2 || exit $?
	echo "$1" >&2
	exit 1
}
gmash_subtree_help() {
cat<<'GETOPTIONSHERE'
gmash subtree <sub-command> [[args]...]
Sub-commands:
Call [main-cmd] [sub-cmd] --help for details of each sub-command.
  new                                   Add and merge a new or existing repo as a subtree to a parent monorepo.
  patch                                 Patch subtree changes to monorepo.
Display:
  -h,     --help                        Display gmash, command or subcommand help. Use -h or --help.
  -v,     --version                     [v0-0-0] Display command group version.
GETOPTIONSHERE
}
# Generated by getoptions (END)
# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.2)
export GMASH_SUBTREE_NEW_URL=''
export GMASH_SUBTREE_NEW_REMOTE=''
export GMASH_SUBTREE_NEW_PATH=''
export GMASH_SUBTREE_NEW_USER=''
export GMASH_SUBTREE_NEW_TGTUSER=''
export GMASH_SUBTREE_NEW_BR=''
export GMASH_SUBTREE_NEW_TGTBR=''
export GMASH_SUBTREE_NEW_NAME=''
GMASH_SUBTREE_NEW_ARGR=''
gmash_parser_subtree_new() {
	OPTIND=$(($#+1))
	while OPTARG= && [ "${GMASH_SUBTREE_NEW_ARGR}" != x ] && [ $# -gt 0 ]; do
		set -- "${1%%\=*}" "${1#*\=}" "$@"
		while [ ${#1} -gt 2 ]; do
			case $1 in (*[!a-zA-Z0-9_-]*) break; esac
			case '--url' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --url"
			esac
			case '--remote' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --remote"
			esac
			case '--path' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --path"
			esac
			case '--user' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --user"
			esac
			case '--tgt-user' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --tgt-user"
			esac
			case '--branch' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --branch"
			esac
			case '--tgt-branch' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --tgt-branch"
			esac
			case '--name' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --name"
			esac
			case '--help' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --help"
			esac
			case '--version' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --version"
			esac
			break
		done
		case ${OPTARG# } in
			*\ *)
				eval "set -- $OPTARG $1 $OPTARG"
				OPTIND=$((($#+1)/2)) OPTARG=$1; shift
				while [ $# -gt "$OPTIND" ]; do OPTARG="$OPTARG, $1"; shift; done
				set "Ambiguous option: $1 (could be $OPTARG)" ambiguous "$@"
				parser_error "$@" >&2 || exit $?
				echo "$1" >&2
				exit 1 ;;
			?*)
				[ "$2" = "$3" ] || OPTARG="$OPTARG=$2"
				shift 3; eval 'set -- "${OPTARG# }"' ${1+'"$@"'}; OPTARG= ;;
			*) shift 2
		esac
		case $1 in
			--?*=*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
				;;
			--no-*|--without-*) unset OPTARG ;;
			-[lRpuUbBn]?*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
				;;
			-[hv]?*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
				case $2 in --*) set -- "$1" unknown "$2" && GMASH_SUBTREE_NEW_ARGR=x; esac;OPTARG= ;;
			+*) unset OPTARG ;;
		esac
		case $1 in
			'-l'|'--url')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_URL="$OPTARG"
				shift ;;
			'-R'|'--remote')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_REMOTE="$OPTARG"
				shift ;;
			'-p'|'--path')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_PATH="$OPTARG"
				shift ;;
			'-u'|'--user')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_USER="$OPTARG"
				shift ;;
			'-U'|'--tgt-user')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_TGTUSER="$OPTARG"
				shift ;;
			'-b'|'--branch')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_BR="$OPTARG"
				shift ;;
			'-B'|'--tgt-branch')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_TGTBR="$OPTARG"
				shift ;;
			'-n'|'--name')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_NEW_NAME="$OPTARG"
				shift ;;
			'-h'|'--help')
				gmash_subtree_new_help
				exit 0 ;;
			'-v'|'--version')
				echo "${GMASH_SUBTREE_NEW_VERSION}"
				exit 0 ;;
			--)
				shift
				while [ $# -gt 0 ]; do
					GMASH_SUBTREE_NEW_ARGR="${GMASH_SUBTREE_NEW_ARGR} \"\${$(($OPTIND-$#))}\""
					shift
				done
				break ;;
			[-+]?*) set "unknown" "$1"; break ;;
			*)
				GMASH_SUBTREE_NEW_ARGR="${GMASH_SUBTREE_NEW_ARGR} \"\${$(($OPTIND-$#))}\""
		esac
		shift
	done
	[ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
	case $1 in
		unknown) set "Unrecognized option: $2" "$@" ;;
		noarg) set "Does not allow an argument: $2" "$@" ;;
		required) set "Requires an argument: $2" "$@" ;;
		pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
		notcmd) set "Not a command: $2" "$@" ;;
		*) set "Validation error ($1): $2" "$@"
	esac
	parser_error "$@" >&2 || exit $?
	echo "$1" >&2
	exit 1
}
gmash_subtree_new_help() {
cat<<'GETOPTIONSHERE'
gmash subtree new
 
Properly add and merge a new or existing repo as a subtree to a parent monorepo.
 
Parameters:
  -l,     --url <remoteURL>             
  -R,     --remote [remote = "origin"]  
  -p,     --path [subtreePath = <subtreeDirName>] 
                                        
  -u,     --user [sourceUser = {currentGithubUser}] 
                                        
  -U,     --tgt-user [targetUser = <sourceUser>] 
                                        
  -b,     --branch [monoBranch = "main"] 
                                        
  -B,     --tgt-branch [subtreeBranch = "main"] 
                                        
  -n,     --name [subtreeDirName = <remoteName>] 
                                        
  
Display:
  -h,     --help                        Display gmash, command or subcommand help. Use -h or --help.
  -v,     --version                     [v0-0-0] Display command group version.
GETOPTIONSHERE
}
# Generated by getoptions (END)
# Generated by getoptions (BEGIN)
# URL: https://github.com/ko1nksm/getoptions (v3.3.2)
export GMASH_SUBTREE_PATCH_REMOTE=''
export GMASH_SUBTREE_PATCH_BRANCH=''
export GMASH_SUBTREE_PATCH_PATH=''
GMASH_SUBTREE_PATCH_ARGR=''
gmash_parser_subtree_patch() {
	OPTIND=$(($#+1))
	while OPTARG= && [ "${GMASH_SUBTREE_PATCH_ARGR}" != x ] && [ $# -gt 0 ]; do
		set -- "${1%%\=*}" "${1#*\=}" "$@"
		while [ ${#1} -gt 2 ]; do
			case $1 in (*[!a-zA-Z0-9_-]*) break; esac
			case '--remote' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --remote"
			esac
			case '--branch' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --branch"
			esac
			case '--path' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --path"
			esac
			case '--help' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --help"
			esac
			case '--version' in
				"$1") OPTARG=; break ;;
				$1*) OPTARG="$OPTARG --version"
			esac
			break
		done
		case ${OPTARG# } in
			*\ *)
				eval "set -- $OPTARG $1 $OPTARG"
				OPTIND=$((($#+1)/2)) OPTARG=$1; shift
				while [ $# -gt "$OPTIND" ]; do OPTARG="$OPTARG, $1"; shift; done
				set "Ambiguous option: $1 (could be $OPTARG)" ambiguous "$@"
				parser_error "$@" >&2 || exit $?
				echo "$1" >&2
				exit 1 ;;
			?*)
				[ "$2" = "$3" ] || OPTARG="$OPTARG=$2"
				shift 3; eval 'set -- "${OPTARG# }"' ${1+'"$@"'}; OPTARG= ;;
			*) shift 2
		esac
		case $1 in
			--?*=*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
				;;
			--no-*|--without-*) unset OPTARG ;;
			-[Rbp]?*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
				;;
			-[hv]?*) OPTARG=$1; shift
				eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
				case $2 in --*) set -- "$1" unknown "$2" && GMASH_SUBTREE_PATCH_ARGR=x; esac;OPTARG= ;;
			+*) unset OPTARG ;;
		esac
		case $1 in
			'-R'|'--remote')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_PATCH_REMOTE="$OPTARG"
				shift ;;
			'-b'|'--branch')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_PATCH_BRANCH="$OPTARG"
				shift ;;
			'-p'|'--path')
				[ $# -le 1 ] && set "required" "$1" && break
				OPTARG=$2
				export GMASH_SUBTREE_PATCH_PATH="$OPTARG"
				shift ;;
			'-h'|'--help')
				gmash_subtree_patch_help
				exit 0 ;;
			'-v'|'--version')
				echo "${GMASH_SUBTREE_PATCH_VERSION}"
				exit 0 ;;
			--)
				shift
				while [ $# -gt 0 ]; do
					GMASH_SUBTREE_PATCH_ARGR="${GMASH_SUBTREE_PATCH_ARGR} \"\${$(($OPTIND-$#))}\""
					shift
				done
				break ;;
			[-+]?*) set "unknown" "$1"; break ;;
			*)
				GMASH_SUBTREE_PATCH_ARGR="${GMASH_SUBTREE_PATCH_ARGR} \"\${$(($OPTIND-$#))}\""
		esac
		shift
	done
	[ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
	case $1 in
		unknown) set "Unrecognized option: $2" "$@" ;;
		noarg) set "Does not allow an argument: $2" "$@" ;;
		required) set "Requires an argument: $2" "$@" ;;
		pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
		notcmd) set "Not a command: $2" "$@" ;;
		*) set "Validation error ($1): $2" "$@"
	esac
	parser_error "$@" >&2 || exit $?
	echo "$1" >&2
	exit 1
}
gmash_subtree_patch_help() {
cat<<'GETOPTIONSHERE'
gmash subtree patch -r [repo] -b [branch]
  
Patch subtree changes to monorepo.
  
Parameters:
  -R,     --remote [remote = "origin"]  
  -b,     --branch [branch = "main"]    
  -p,     --path <subtreePath>          
  
Display:
  -h,     --help                        Display gmash, command or subcommand help. Use -h or --help.
  -v,     --version                     [v0-0-0] Display command group version.
GETOPTIONSHERE
}
# Generated by getoptions (END)
