# Reference:
# https://just-the-docs.com/docs/configuration/
title: gmash docs
remote_theme: just-the-docs/just-the-docs

# Configure search
search_enabled: true

# Configure navigation
nav_order: 1
nav_fold: false # Whether to fold navigation items by default

# Color scheme supports "light" (default) and "dark"
color_scheme: dark